import Image from 'next/image';

function SkillsAndTech() {
  return (
    <div className="content-wrapper">
      <h1 className=" text-3xl font-bold">🔨 My Arsenal </h1>
      <div className="image-container mt-4 flex flex-wrap justify-center space-x-4 space-y-4">
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original-wordmark.svg"
          alt="java"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg"
          alt="C"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg"
          alt="Python"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg"
          alt="C++"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg"
          alt="spring"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apache/apache-original-wordmark.svg"
          alt="apache"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg"
          alt="azure"
          height="50"
          width="50"
        />

        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg"
          alt="C++"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg"
          alt="Flask"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
          alt="Git"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg"
          alt="Github"
          height="50"
          width="50"
        />
        <Image
          src="https://www.vectorlogo.zone/logos/hibernate/hibernate-icon.svg"
          alt="Hibernate"
          height="50"
          width="50"
        />
        <Image
          src="/assets/images/logo/file_type_maven.svg"
          alt="Maven"
          height="50"
          width="50"
          crossOrigin=""
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/intellij/intellij-original.svg"
          alt="Intellij"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original-wordmark.svg"
          alt="Jira"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/latex/latex-original.svg"
          alt="Latex"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg"
          alt="Mysql"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg"
          alt="Oracle"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg"
          alt="Postgress"
          height="50"
          width="50"
        />

        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain-wordmark.svg"
          alt="SqlServer"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg"
          alt="TensorFlow"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg"
          alt="OpenCv"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pycharm/pycharm-original.svg"
          alt="PyCharm"
          height="50"
          width="50"
        />
        <Image
          src="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
          alt="Postman"
          height="50"
          width="50"
        />
        <Image
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg"
          alt="Docker"
          height="50"
          width="50"
        />
      </div>
    </div>
  );
}

export default SkillsAndTech;
